# Copied & modified from GTCEu actions.
# https://github.com/GregTechCEu/GregTech/blob/master/.github/actions/build_setup/action.yml
# Distributed under the LGPL-3.0 License: https://github.com/GregTechCEu/GregTech/blob/master/LICENSE

name: Build Setup
description: Setup for standard Java builds

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: "false"

runs:
  using: 'composite'

  steps:

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

    - name: Setup Java
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: |
          8
          21
        distribution: zulu

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      with:
        cache-write-only: ${{ inputs.update-cache }}
        gradle-home-cache-includes: |
          caches
          caches/retro_futura_gradle
          notifications
          jdks
          wrapper
